apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "certbot.fullname" . }}
  labels: {{ include "certbot.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  jobTemplate:
    metadata:
      labels: {{ include "certbot.labels" . | nindent 8 }}
    spec: {{ include "certbot.jobSpec" . | nindent 6 }}
  schedule: {{ .Values.cron.schedule }}
  suspend: {{ .Values.cron.suspend }}
