apiVersion: v1
kind: Template
metadata: 
  creationTimestamp: null
  name: certbot
parameters:
- name: GIT_REF
  value: 'master'
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: certbot
    name: certbot
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: certbot
    name: certbot
  spec:
    nodeSelector: null
    completionDeadlineSeconds: 300
    output:
      to:
        kind: ImageStreamTag
        name: certbot:latest
    postCommit: {}
    resources:
      requests:
        cpu: 1
      limits:
        cpu: 1
    source:
      contextDir: docker
      git:
        uri: https://github.com/BCDevOps/certbot.git
        ref: '${GIT_REF}'
      type: Git
    strategy:
      dockerStrategy: { }
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0